= forth-turf
Forth snippets.

My daily driver is a late 2013
https://support.apple.com/kb/SP690?locale=en_US&viewlocale=de_DE[MacBook Pro].

- 2,600 €
- 2,3 GHz Quad‑Core Intel Core i7, Turbo Boost up to 3.5 GHz
- 16 GB RAM

I also own a STM32F103, aka the _blue pill_.

- 2 €
- 72 MHz Arm M3
- 20 KB RAM

== Comparing host environments

I'm not comparing apples to oranges, but a big apple to a small apple. 
Both qualify as a 'Computer'.
On the Mac i picked gforth because it just falls out of homebrew.
On the blue pill, i use http://mecrisp.sourceforge.net[mecrisp].

=== Price

----
☐ (1)
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐ (2)
----
(1) blue pill
(2) MacBook Pro

=== CPU frequency

----
☐ (1)
☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐☐ (2)
----
(1) blue pill
(2) MacBook Pro

=== RAM

I'd better not show the RAM ratio here.
Just doing some rough calculations: 20 KB is 20e3, 16 GB is 16e9, which is one
million times 20 KB. `838860`, to be precise. 

== Running

To run the gforth samples, i use

----
gforth euler1.4th -e bye
----

`bye` is the command to exit the REPL in gforth.

On the blue pill, i fire up `picocom` and copy-paste stuff.

== Project Euler

=== Problem #1

Commit
https://github.com/jhinrichsen/forth-turf/commit/1f144cace536896500b3b011281ff0ae443bf80f[1f144cac]
is the first version that runs in 2983 resp. 2984 μs, i.e. 3 ms.

Variant 1 inlines `: mod3 3 mod 0= ;`.

Variant 2 uses short circuit evalutation of mod 3 _or_ mod 5.

Variant 3 avoids `if` when adding to sum, instead it 0s non-multiples.
I was hoping for some benefits in branch prediction which do not show up.

Variant 4 uses multiples of 3 + multiples of 5 - multiples of 15 (worms)

[options="header"]
|====
| Algorithm | Runtime | Performance increase
| Baseline  | 2893 µs | 
| Variant 1 | 2532 µs | 12 % faster, 88% of baseline
| Variant 2 | 2241 µs | 12 % faster, 77% of baseline
| Variant 3 | 2188 µs | 3 % faster, 75% of baseline
| Variant 4 |  161 µs | 93 % faster, 5% of baseline
|====

== Comparison to other implementations

I implemented Euler problem #1 in a variety of languages, not all algorithms are
comparable though (lazy evaluation, concurrency e.a.).

=== Algorithms

Algo #1: straight seq
- sum = 0
- for all indices < N:
	- if index modulo 3 is 0, and index modulo 5 is 0:
		- add index to sum
- return sum

Algo #2: add multiples
- return multiples of 3 + multiples of 5 - multiples of 15 where index < N

Algo #3: multithreaded #2

=== Results

Forth timings are on the blue pill, all others on a MacBook Pro.

Clojure 1.10, OpenJDK 12

Go 1.13, `go test -bench=.`

Node.js 12.11, `npm test`

Rust nightly 1.40, `cargo bench`


All timings in µs, i.e. 10^-6^ seconds.

[options="header"]
|====
| Algorithm | Clojure | Forth |       Go         | Node.js | Rust
| Algo #1   |  3,500  |  2188 |   1.6 (1,645 ns) |     650 | 3 (2,700 ns) 
| Algo #2   |    700  |   161 |   0.2   (236 ns) |         |
| Algo #3   |  5,600  |       | 323              |         |
|====
